### PR TITLE
Implement fastclick.js library to remove the 300ms delay on Safari/iOS

### PR DESCRIPTION
**Pull request by bjornhij**

### CODE REVIEW

**Comment by sweetpi** [comment]
Big thanks for the pull request. I finally found some time testing (on android). It seems that switching tabs does not work reliable on android with fastcklick enabled. I have to take a deeper look at this.

Are the problem for ios solved with the fastclick integration?

**Comment by sweetpi** [comment]
Found a fix. Merged and published your pull request with 0.8.67.

**Comment by bjornhij** [comment]
Thx! Yes, this definitely makes a difference on IOS in terms of responsiveness.

**Comment by sweetpi** [comment]
Nice!

**Comment by Yves911** [comment]
I can confirm that now the UI is much more responsive than before.
Thanks guys!

**Comment by sweebee** [comment]
Wow, just saw these Messages but it didnt know what the problem was. But it feels like a native app now, so quick

**Pull request merged**
